      program main
      integer Np
      Np = 32149
      write(*, '(A)') '<?xml version="1.0" encoding="UTF-8"?>'
      write(*, '(A)') '<Xdmf Version="2.0">'
      write(*, '(A)') '  <Domain>'
      write(*, '(A)') '    <Grid>'
      write(*, '(A)') '      <Topology'
      write(*, '(A)') '	  TopologyType="Polyvertex">'
      write(*, '(A)') '      </Topology>'
      write(*, '(A)') '      <Geometry'
      write(*, '(A)') '	  GeometryType="XY">'
      write(*, '(A)') '	<DataItem'
      write(*, '(A)') '	    ItemType="HyperSlab"'
      write(*, '(''	    Dimensions="'' I8, I8, ''">'')') Np, 2
      write(*, '(A)') '	  <DataItem'
      write(*, '(A)') '	      Dimensions="3 2"'
      write(*, '(A)') '	      Format="XML">'
      write(*, '(A)') '	    0 0'
      write(*, '(A)') '	    1 1'
      write(*, '(''	    '', I8, I8)') Np, 2
      write(*, '(A)') '	  </DataItem>'
      write(*, '(A)') '   <DataItem'
      write(*, '(    ''       Dimensions="'' I8, I8, ''">'')') Np, 3
      write(*, '(A)') '	      Format="Binary">'
      write(*, '(A)') '	    p.00000000.raw'
      write(*, '(A)') '	  </DataItem>'
      write(*, '(A)') '	</DataItem>'
      write(*, '(A)') '      </Geometry>'
      write(*, '(A)') '      <Attribute'
      write(*, '(A)') '	  Name="circ">'
      write(*, '(A)') '	<DataItem'
      write(*, '(A)') '	    ItemType="HyperSlab"'
      write(*, '(A)') '	    Dimensions="32149">'
      write(*, '(A)') '	  <DataItem'
      write(*, '(A)') '	      Dimensions="3"'
      write(*, '(A)') '	      Format="XML">'
      write(*, '(A)') '	    2'
      write(*, '(A)') '	    3'
      write(*, '(A)') '	    96447'
      write(*, '(A)') '	  </DataItem>'
      write(*, '(A)') '	  <DataItem'
      write(*, '(A)') '	      Dimensions="96447"'
      write(*, '(A)') '	      Format="Binary">'
      write(*, '(A)') '	    p.00000000.raw'
      write(*, '(A)') '	  </DataItem>'
      write(*, '(A)') '	</DataItem>'
      write(*, '(A)') '      </Attribute>'
      write(*, '(A)') '    </Grid>'
      write(*, '(A)') '  </Domain>'
      write(*, '(A)') '</Xdmf>'
      end
