#!/bin/awk -f

BEGIN {
      s = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 =+-*/().,$':"
}

{
    l = toupper($0)
    for (i = 1; i <= length(l); i++) {
	for (j = 1; j <= length(s); j++)
	    if ("" substr(l, i, 1) == substr(s, j, 1))
		break
	if (j > length(s)) {
	    printf "%s:%d:%d:%s\n", FILENAME, NR, i, $0
	    next
	}
    }
}
